apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app.kubernetes.io/name: http-server
    app.kubernetes.io/component: web

spec:
  containers:
    - name: web
      image: http-server:latest
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 8000
          name: http
    - name: proxy
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http